version: '3.8'
services:
  web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - ./src:/code
          - ./server/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      build: server/.
      volumes:
          - ./src:/code
  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
        MARIADB_ROOT_PASSWORD: qwerty
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8000:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db